import { Button, DemoLabel, Eyebrow } from '../../components/UI';
import {brand} from '../../config/brand';
import type {Screen} from '../../types';
export function CustomerExperience({screen,reward,setReward,go}: {screen:Screen;reward:string|null;setReward:(id:string)=>void;go:(screen:Screen)=>void}) {
 const selected=brand.rewardOptions.find(x=>x.id===reward);
 if(screen==='purchase') return <section className="customer-layout page-enter"><div className="customer-copy"><Eyebrow>01 / تجربة العميل</Eyebrow><h1>قهوتك جاهزة <span className="coffee-emoji" aria-hidden="true">☕</span><br/><span>وقصتنا لسه بتبدأ.</span></h1><p className="lead">سجّل زيارتك وابدأ رحلتك مع {brand.businessName}.</p><p>زيارة بسيطة. سبب جديد للعودة.<br/>من دون بيانات شخصية في هذه التجربة.</p><div className="assurance"><span aria-hidden="true">✓</span> لن يتم حفظ أو إرسال أي بيانات.</div></div><div className="customer-card"><div className="receipt-top"><DemoLabel>سيناريو شراء تجريبي</DemoLabel><strong>{brand.businessName}</strong><span>{brand.businessType}</span></div><div className="receipt-rule"/><div className="receipt-item"><span>قهوة اليوم</span><b>جاهزة ✓</b></div><div className="receipt-dashed"/><h2>خلي الزيارة دي<br/>أول خطوة.</h2><p>ابدأ رحلة قصيرة نحو مكافأة تختارها بنفسك.</p><Button onClick={()=>go('reward')}>متابعة كتجربة</Button><small>لا نحتاج إلى رقم جوالك.</small></div></section>;
 if(screen==='reward') return <section className="reward-page page-enter"><Eyebrow>01 / زيارة مسجلة</Eyebrow><div className="reward-intro"><div><h1>أهلًا بك في {brand.businessName}.<br/><span>اختر ما تحب العودة له.</span></h1><p className="lead">تم تسجيل زيارتك الأولى ✓</p></div><div className="visit-progress"><span className="visit-fraction" dir="ltr">1 <small>/ 3</small></span><div className="small-stamps"><b>✓</b><span>2</span><span>3</span></div><p>باقي زيارتان للوصول إلى مكافأتك الأولى.</p></div></div><div className="reward-options" role="group" aria-label="اختر مكافأتك المفضلة">{brand.rewardOptions.map((item,index)=><button type="button" key={item.id} aria-pressed={reward===item.id} className={`reward-option ${reward===item.id?'selected':''}`} onClick={()=>setReward(item.id)}><div className="reward-option-top"><span className="reward-symbol" aria-hidden="true">{item.symbol}</span><span className="selection-check" aria-hidden="true">{reward===item.id?'✓':`0${index+1}`}</span></div><h2>{item.title}</h2><p>{item.detail}</p><span className="reward-bottom">{reward===item.id?'هذه مكافأتي المفضلة':'اختر هذه المكافأة'}</span></button>)}</div><div className="reward-footer"><div><p aria-live="polite">{selected?`اختيارك يساعد ${brand.businessName} على تقديم مكافآت أقرب لتفضيلاتك.`:'أي تجربة تفضّل في زيارتك القادمة؟'}</p><small>خيارات توضيحية؛ أنواع المكافآت وشروطها يحددها النشاط لاحقًا. الاختيار لا يُحفظ.</small></div><Button disabled={!reward} onClick={()=>go('return')}>متابعة الرحلة</Button></div></section>;
 return <section className="return-layout page-enter"><div className="return-copy"><Eyebrow>02 / سبب للعودة</Eyebrow><h1>الهدف مش إنك<br/>تجمع نقاط <span>وخلاص.</span></h1><p className="lead">الفكرة إن كل زيارة يكون لها سبب يخلي تجربتك القادمة أفضل.</p><div className="chosen-reward"><span aria-hidden="true">✦</span><div><small>اختيارك في هذه التجربة</small><strong>{selected?.title??'مكافأة أقرب لتفضيلك'}</strong></div></div><Button onClick={()=>go('bridge')}>شاهد ما يراه {brand.businessName}</Button></div><div className="journey-card"><span className="eyebrow">علاقة تنمو مع كل زيارة</span>{['الزيارة الأولى','الزيارة الثانية','عميل متكرر','مكافآت وتجربة أكثر ملاءمة'].map((label,i)=><div className={`journey-step ${i===0?'complete':''}`} key={label}><span>{i===0?'✓':`0${i+1}`}</span><div><h2>{label}</h2><p>{['بداية التعارف','سبب جديد للاختيار','تفضيل يتحول إلى عادة','تجربة تتطور بموافقة العميل'][i]}</p></div></div>)}</div></section>;
}
