import {Button,DemoLabel,Eyebrow,SectionTitle} from '../../components/UI';
import {brand} from '../../config/brand';
import {DropFunnel} from './DropFunnel';
import {DropBusinessMetrics} from './DropBusinessMetrics';
import {BusinessObjective} from './BusinessObjective';
import {GrowthLoop} from './GrowthLoop';
import './drop.css';
export default function DropBusinessView({completed,onRetention,onDashboard}: {completed:boolean;onRetention:()=>void;onDashboard:()=>void}) {
 return <div className="drop-business page-enter"><div className="demo-banner" role="note"><span aria-hidden="true">ⓘ</span><b>بيانات تجريبية لتوضيح آلية القياس — ليست بيانات {brand.businessName} الفعلية.</b><span className="demo-pill" dir="ltr">DEMO DATA</span></div><div className="dashboard-title"><div><Eyebrow>من تجربة مختلفة إلى نتيجة أوضح</Eyebrow><h1>ماذا يمكن أن يعرف النشاط<br/><span>من تجربة كهذه؟</span></h1><p><bdi>HAFNA DROP #001</bdi> · تصور لفرصة نمو محتملة</p></div><DemoLabel>{completed?'أكملت محاكاة الـPass':'رؤية النشاط التجريبية'}</DemoLabel></div><div className="drop-business-grid"><DropFunnel/><aside className="drop-business-insight"><span className="drop-code" dir="ltr">BEYOND THE VIEWS</span><h2>2,410 مشاهدة.<br/><span>وماذا بعدها؟</span></h2><p>نبحث عن زيارة وشراء وعودة، بدل الاكتفاء بالانتشار.</p><div className="drop-business-stat"><strong>163</strong><span>استخدامًا افتراضيًا للـPass</span></div><div className="drop-business-stat"><strong>31</strong><span>عودة افتراضية في تجربة لاحقة</span></div><small>هذه بيانات عرض ثابتة؛ محاكاتك لا تُضاف إلى هذه المقاييس ولا تمثل عملية بيع فعلية.</small></aside></div><section className="drop-retention-bridge"><Eyebrow light>هنا تبدأ قيمة العلاقة</Eyebrow><h2>لكن الزيارة الأولى<br/><span>ليست نهاية العلاقة.</span></h2><p>ماذا يحدث بعد أن يجرب العميل الـDROP؟</p><div className="drop-followup">{['هل عاد العميل؟','هل قام بشراء ثانٍ؟','هل أصبح عميلًا متكررًا؟','هل بدأ ينقطع؟','هل عاد بعد تجربة أو حملة أخرى؟'].map(text=><span key={text}>{text}</span>)}</div><p className="bridge-condition">يمكن فهم ذلك عند وجود آلية مناسبة وموافقة العميل حيث يلزم. أرقام الـDROP ولوحة العودة مجموعتان تجريبيتان مستقلتان؛ الربط هنا يوضح الفكرة.</p><div className="drop-bridge-actions"><Button onClick={onRetention}>تابع رحلة العميل بعد الزيارة</Button><button className="text-button" onClick={onDashboard}>افتح لوحة العودة الحالية</button></div></section><DropBusinessMetrics/><BusinessObjective/><GrowthLoop/><section className="drop-operations"><SectionTitle number="04" title="كيف يمكن تشغيل تجربة كهذه؟"/><ol className="operation-steps">{[['رابط أو رمز دخول','QR / Link'],['تجربة على الويب','Web Experience'],['بطاقة تجربة','Digital Pass'],['تحقق بسيط','Simple Verification'],['قياس النتيجة','Measurement']].map(([ar,en],i)=><li key={en}><span dir="ltr">0{i+1}</span><b>{ar}</b><small lang="en" dir="ltr">{en}</small></li>)}</ol><p>الفكرة المبدئية هي اختبار التجربة بأقل تغيير ممكن في تشغيل النشاط، دون فرض تطبيق جديد على العميل أو تغيير نظام الكاشير بالكامل.</p><small>يمكن دراسة التكامل مع POS أو الأنظمة الحالية لاحقًا إذا أثبتت التجربة قيمتها وكان التكامل متاحًا.</small></section><section className="drop-nexora-note"><h2>النتيجة هي نقطة البداية.</h2><p>NEXORA تحدد نتيجة تجارية أو فرصة نمو، ثم تصمم تجربة أو حلًا مناسبًا، وتقيس النتيجة وتستخدم ما تعلمته لتحسين الخطوة التالية. HAFNA DROP مجرد مثال واحد على ذلك.</p><Button onClick={onDashboard}>انتقل إلى قياس العودة والاحتفاظ</Button></section></div>;
}
