import {useEffect,useRef,useState} from 'react';
import {Button,DemoLabel,Modal} from '../../components/UI';
import {mockCampaign} from '../../data/mockData';
import {formatNumber} from '../../utils/calculator';
export function CampaignSimulator({onClose,onFinish}: {onClose:()=>void;onFinish:()=>void}) {
 const [message,setMessage]=useState('اشتقنا لك ☕\nزيارتك القادمة لها مفاجأة خاصة.');
 const [status,setStatus]=useState<'edit'|'running'|'result'>('edit');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 function simulate(){setStatus('running');timer.current=setTimeout(()=>setStatus('result'),1500);}
 return <Modal title={status==='result'?'عودة قابلة للقياس.':status==='running'?'نحاكي أثر التدخل…':'دعوة صغيرة. فرصة للعودة.'} onClose={onClose}><DemoLabel>محاكاة فقط — لا تُرسل أي رسائل</DemoLabel>{status==='edit'?<><div className="campaign-segment"><span className="segment-icon" aria-hidden="true">◷</span><div><small>المجموعة المستهدفة · سيناريو تجريبي</small><strong>عملاء منتظمون لم يعودوا منذ {mockCampaign.inactiveDays} يومًا</strong></div><b>{mockCampaign.targeted}<small> عميلًا</small></b></div><label className="input-label" htmlFor="campaign-message">نص الرسالة التجريبية</label><textarea id="campaign-message" rows={3} maxLength={500} value={message} onChange={e=>setMessage(e.target.value)}/><div className="message-preview"><span>معاينة الرسالة</span><p>{message||'اكتب رسالتك لتظهر هنا.'}</p><small>تجربة العرض · لن تُرسل</small></div><p className="fine-print">في التطبيق الفعلي نحدد القناة والمكافأة وموافقة العميل، ثم نقيس العودة ضمن فترة واضحة.</p><Button disabled={!message.trim()} onClick={simulate}>تشغيل محاكاة الحملة</Button></>:status==='running'?<div className="simulation-wait" role="status"><div className="simulation-loader"/><h3>مرور الوقت في سيناريو افتراضي</h3><p>نقارن المستهدفين بالعملاء الذين عادوا.</p><div className="simulation-progress"/></div>:<div className="simulation-result" aria-live="polite"><p className="result-disclaimer">نتيجة افتراضية لأغراض العرض فقط.</p><div className="result-metrics">{[['تم استهداف',mockCampaign.targeted],['عاد منهم',mockCampaign.returned],['معدل الاسترجاع',`${formatNumber(mockCampaign.returned/mockCampaign.targeted*100)}%`],['عمليات شراء إضافية',mockCampaign.extraPurchases]].map(([label,value])=><div key={label}><span>{label}</span><strong dir="ltr">{value}</strong></div>)}</div><div className="result-insight"><b>كل رقم قابل للقياس في النظام الحقيقي.</b><p>معدل الاسترجاع = 7 ÷ 23 × 100 = 30.4%<br/>تعديل الرسالة لا يغيّر هذه النتيجة الافتراضية؛ ولا يثبت أن الحملة وحدها سببت العودة.</p></div><div className="modal-actions"><Button onClick={onFinish}>ما الذي تعنيه هذه الأرقام؟</Button><Button secondary onClick={()=>setStatus('edit')}>تعديل المحاكاة</Button></div></div>}</Modal>;
}
