import {useState} from 'react';
import {Button,Eyebrow,Modal} from '../components/UI';
import {brand} from '../config/brand';
import {getWhatsAppUrl} from '../config/contact';
export function Closing({onBack}: {onBack:()=>void}) {
 const [dialog,setDialog]=useState<'existing'|'more'|null>(null);
 const url=getWhatsAppUrl();
 return <section className="closing page-enter"><Eyebrow>04 / قرار يبدأ بفهم الواقع</Eyebrow><div className="closing-layout"><div><span className="nexora closing-wordmark" dir="ltr">NEXORA ↗</span><h1>هذه ليست منصة جاهزة<br/><span>نحاول بيعها لكم.</span></h1><p className="lead">هذا تصور بنته NEXORA خصيصًا لـ{brand.businessName} لاستكشاف فرصة محتملة: خلق سبب جديد للزيارة، ثم قياس تحوّل التجربة إلى زيارة وشراء وعودة.</p><p>إذا كان لديكم بالفعل نظام يؤدي هذه الوظيفة، فهذا ممتاز.</p><p>وإذا لم يكن موجودًا وكانت هذه الفرصة مهمة لكم، نفهم التشغيل الفعلي لـ{brand.businessName} ونصمم اختبارًا صغيرًا قابلًا للقياس قبل بناء أي نظام كبير.</p><div className="closing-actions"><Button onClick={()=>setDialog('more')}>أريد معرفة المزيد</Button><Button secondary onClick={()=>setDialog('existing')}>لدينا نظام مشابه</Button></div><button className="text-button" onClick={onBack}>العودة إلى رؤية النشاط</button></div><aside className="closing-card"><span className="eyebrow">الفكرة تبدأ من هنا</span><h2>هل أنا أصلًا<br/>بعرف كام عميل<br/><span>بيرجع لي؟</span></h2><div className="closing-card-rule"/><ol><li>نفهم الواقع</li><li>نتحقق من الفرصة</li><li>نصمم الحل</li><li>نقيس الأثر</li></ol><small>التقنية أداة. النتيجة هي البداية.</small></aside></div>{dialog?<Modal title={dialog==='existing'?'ممتاز 👌':'الخطوة التالية بسيطة.'} onClose={()=>setDialog(null)}>{dialog==='existing'?<><p className="lead">هدفنا ليس استبدال شيء يعمل بالفعل.</p><p>إذا أحببتم، يمكن لـNEXORA النظر في جزء آخر من رحلة العميل أو التشغيل واكتشاف فرصة مختلفة.</p><Button onClick={()=>setDialog(null)}>العودة</Button></>:<><p className="lead">نحتاج فقط معرفة كيف تعمل رحلة العميل عندكم حاليًا، وبعدها نحدد هل الفكرة تستحق التنفيذ أصلًا.</p><div className="next-questions"><p>هل لديكم حاليًا نظام أو طريقة تؤدي وظيفة مشابهة؟</p><p>إذا لا، هل هذه الفرصة مهمة لكم؟</p></div><div className="message-preview"><span>الرسالة الجاهزة</span><p>{brand.contact.message}</p></div>{url?<a className="button" href={url} target="_blank" rel="noopener noreferrer">التواصل عبر WhatsApp</a>:<><Button disabled>التواصل عبر WhatsApp</Button><p className="fine-print">لم يُضف رقم التواصل بعد. يُفعّل الزر عند إعداد الرقم الحقيقي.</p></>}<Button secondary onClick={()=>setDialog(null)}>العودة</Button></>}</Modal>:null}</section>;
}
